name: blockwallet
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  
  geolocator: ^13.0.1
  geofencing_api: ^2.0.0
  open_route_service: ^1.2.6
  cupertino_icons: ^1.0.8
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.5
  permission_handler: ^11.3.1
  flutter_lints: ^4.0.0
  http: ^1.2.2
  maps_toolkit: ^3.1.0
  flutter_launcher_icons: ^0.14.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.15
  hive_generator: ^2.0.1


  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  web3dart: ^2.7.3
  shared_preferences: ^2.4.0 # for storing wallet addresses
  provider: ^6.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/appstore.png"

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logo/
    - assets/abi/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf        
        - asset: assets/fonts/Poppins-Medium.ttf        
        - asset: assets/fonts/Poppins-SemiBold.ttf        
        - asset: assets/fonts/Poppins-Bold.ttf      
        - asset: assets/fonts/Poppins-ExtraBold.ttf         
        - asset: assets/fonts/Poppins-Black.ttf

